spring.application.name=ranadj

spring.datasource.url=${dburl}
spring.datasource.username=${dbname}
spring.datasource.password=${dbpassword}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=ranadjverysecuresecretkeyforjwtgeneration
jwt.expiration=86400000

# Razorpay Configuration Keys (Test Credentials)
razorpay.key.id=${Razkeyid}
razorpay.key.secret=${Razkeysecret}

# Azure Blob Storage Configuration
azure.storage.connection-string=${containerstring}
azure.storage.container-name=${containername}

# File Upload Size Limits
spring.servlet.multipart.max-file-size=250MB
spring.servlet.multipart.max-request-size=250MB
